name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  playwright:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          npm ci
          npm install -g serve
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build app
        run: npm run build
      - name: Run Server and Playwright tests
        run: npm run start:test
        env:
          DEBUG: pw:api
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
